VERT
DCL IN[0], POSITION
DCL IN[1], COLOR
DCL CONST[0], modelViewProj[0]
DCL CONST[1], modelViewProj[1]
DCL CONST[2], modelViewProj[2]
DCL CONST[3], modelViewProj[3]
DCL OUT[0], POSITION
DCL OUT[1], GENERIC[0]

DP4 OUT[0].x, IN[0], CONST[0]
DP4 OUT[0].y, IN[0], CONST[1]
DP4 OUT[0].z, IN[0], CONST[2]
DP4 OUT[0].w, IN[0], CONST[3]
ABS TEMP[0], IN[1]
MIN TEMP[1], TEMP[0], IN[1]
MAX TEMP[2], TEMP[1], TEMP[0]
SLT TEMP[3], TEMP[2], IN[0]
SGE TEMP[4], TEMP[3], IN[1]
SEQ TEMP[5], TEMP[4], TEMP[0]
SNE TEMP[6], TEMP[5], TEMP[1]
FRC TEMP[7], TEMP[6]
FLR TEMP[8], TEMP[7]
MAD OUT[1], TEMP[8], IN[1], TEMP[0]
END
