/**
 * PS3 Reality Synthesizer (RSX) - Shader Model 3.0 Conformance Test Shader Generator
 *
 * Standalone C utility to generate discrete .fcg shader source files for RSX Shader Model 3.0
 * conformance tests with comprehensive inline comments explaining the mathematical theory,
 * RSX hardware ALU instructions, and visual verification semantics.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#define MAX_PATH_LEN 1024

typedef struct {
    const char* filename;
    const char* content;
} ShaderTemplate;

static const ShaderTemplate g_shaders[] = {
    {
        "test_03_sub.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 03: sub / - (Shader Model 3.0 Basic Arithmetic)\n"
        "// Mathematical subtraction of dynamic chromatic bands from background gradient\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    // Smooth base background gradient across NDC UV [-1, 1]\n"
        "    float3 base_bg = float3(0.9, 0.85, 0.7);\n"
        "    \n"
        "    // Moving animated light beam to subtract\n"
        "    float beam = max(0.0, 1.0 - abs(input.uv.x - sin(t * 2.0) * 0.7) * 4.0);\n"
        "    float3 sub_color = float3(beam * 0.8, beam * 0.5, beam * 0.2);\n"
        "    \n"
        "    // Evaluate hardware SUB: base_bg - sub_color creates inverted dark shadow band\n"
        "    float3 result = base_bg - sub_color;\n"
        "    \n"
        "    output.color = float4(result, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_04_mul.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 04: mul / * (Shader Model 3.0 Basic Arithmetic)\n"
        "// Multiplicative color modulation combining rotating 2D grid with radial vignette\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    // Rotating 2D pattern coordinate\n"
        "    float cos_t = cos(t);\n"
        "    float sin_t = sin(t);\n"
        "    float2 rot_uv = float2(input.uv.x * cos_t - input.uv.y * sin_t, input.uv.x * sin_t + input.uv.y * cos_t);\n"
        "    \n"
        "    float3 grid_col = float3(sin(rot_uv.x * 8.0) * 0.5 + 0.5, cos(rot_uv.y * 8.0) * 0.5 + 0.5, 0.8);\n"
        "    float vignette = max(0.0, 1.0 - length(input.uv) * 0.7);\n"
        "    \n"
        "    // Evaluate hardware MUL: grid_col * vignette\n"
        "    float3 result = grid_col * vignette;\n"
        "    \n"
        "    output.color = float4(result, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_05_mad.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 05: mad / fma (Shader Model 3.0 Basic Arithmetic)\n"
        "// Single-cycle Fused Multiply-Add (a * b + c) computing frequency modulation rings\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float dist = length(input.uv);\n"
        "    float wave_carrier = sin(dist * 16.0 - t * 4.0);\n"
        "    float wave_mod = cos(input.uv.x * 8.0 + t);\n"
        "    \n"
        "    // Native RSX MAD: carrier * mod + bias\n"
        "    float3 result = float3(wave_carrier * wave_mod + 0.5, wave_carrier * 0.5 + 0.5, wave_mod * 0.5 + 0.5);\n"
        "    \n"
        "    output.color = float4(result, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_06_div.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 06: div / / (Shader Model 3.0 Basic Arithmetic)\n"
        "// Spatial division creating quantized radial cell segments via RCP + MUL pipeline\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float scale = 0.25 + 0.15 * sin(t * 2.0);\n"
        "    // RSX Hardware Division: evaluated via RCP and MUL\n"
        "    float2 divided_uv = input.uv / scale;\n"
        "    float3 col = float3(frac(divided_uv.x), frac(divided_uv.y), 0.5);\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_07_rcp.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 07: rcp (Shader Model 3.0 Basic Arithmetic)\n"
        "// Hardware 1/x Reciprocal instruction generating hyperbolic core illumination\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float d = length(input.uv) * 2.0 + 0.05;\n"
        "    // RSX Hardware 1/x\n"
        "    float inv_d = 1.0 / d;\n"
        "    float pulse = 0.5 + 0.5 * sin(t * 3.0);\n"
        "    float3 col = float3(inv_d * 0.2 * pulse, inv_d * 0.1, inv_d * 0.05);\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_08_rsq.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 08: rsqrt / rsq (Shader Model 3.0 Basic Arithmetic)\n"
        "// Hardware 1 / sqrt(x) Reciprocal Square Root instruction for point light decay\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float d_sq = dot(input.uv, input.uv) * 4.0 + 0.02;\n"
        "    // RSX Hardware RSQ: 1.0 / sqrt(d_sq)\n"
        "    float inv_sqrt = rsqrt(d_sq);\n"
        "    \n"
        "    float glow = inv_sqrt * (0.4 + 0.2 * sin(t * 4.0));\n"
        "    float3 col = float3(glow * 0.3, glow * 0.7, glow * 1.0);\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_09_sqrt.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 09: sqrt (Shader Model 3.0 Basic Arithmetic)\n"
        "// Square root instruction pipeline generating parabolic radial gradient profile\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    // Radial Euclidean distance from center\n"
        "    float dist = length(input.uv);\n"
        "    \n"
        "    // Square root calculation: RSQ + RCP or RSQ + MUL\n"
        "    // Parabolic expansion curve mapping [0, 1] distance to concave sqrt gradient\n"
        "    float s = sqrt(dist);\n"
        "    \n"
        "    // Outward-propagating harmonic wave modulated by sqrt curve\n"
        "    float wave = sin(s * 12.0 - t * 4.0) * 0.5 + 0.5;\n"
        "    float3 col = float3(s, wave, 1.0 - s);\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_10_abs.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 10: abs (Shader Model 3.0 Basic Arithmetic)\n"
        "// Register Absolute Value modifier generating perfect 4-quadrant mirror kaleidoscope\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    // Hardware Absolute Bit: abs(input.uv)\n"
        "    float2 sym_uv = abs(input.uv);\n"
        "    \n"
        "    float pattern = sin((sym_uv.x + sym_uv.y) * 12.0 - t * 2.0) * 0.5 + 0.5;\n"
        "    float3 col = float3(sym_uv.x, pattern, sym_uv.y);\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_11_neg.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 11: neg / -x (Shader Model 3.0 Basic Arithmetic)\n"
        "// Register Negate modifier creating inverse chromatic phase sweep\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    // Hardware Operand Negate bit\n"
        "    float2 neg_uv = -input.uv;\n"
        "    \n"
        "    float val = sin(neg_uv.x * 6.0 + neg_uv.y * 6.0 + t * 3.0) * 0.5 + 0.5;\n"
        "    float3 col = float3(1.0 - val, neg_uv.x * 0.5 + 0.5, neg_uv.y * 0.5 + 0.5);\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_12_sin.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 12: sin (Shader Model 3.0 Trigonometry)\n"
        "// Hardware Taylor/Chebyshev Trigonometric SIN ALU evaluating outward concentric wave ripples\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float dist = length(input.uv * 8.0);\n"
        "    // Native RSX SIN ALU\n"
        "    float wave = sin(dist - t * 5.0) * 0.5 + 0.5;\n"
        "    \n"
        "    float3 col = float3(wave * 0.9, wave * 0.4, 1.0 - wave);\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_13_cos.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 13: cos (Shader Model 3.0 Trigonometry)\n"
        "// Hardware Trigonometric COS ALU producing 90-degree phase shifted harmonic moire pattern\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float dist = length(input.uv * 8.0);\n"
        "    // Native RSX COS ALU (exact 90-degree quadrature phase relative to sin)\n"
        "    float wave = cos(dist - t * 5.0) * 0.5 + 0.5;\n"
        "    \n"
        "    float3 col = float3(1.0 - wave, wave * 0.8, wave * 0.3);\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_14_tan.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 14: tan (Shader Model 3.0 Trigonometry)\n"
        "// Trigonometric Tangent (sin/cos/rcp/mul) generating periodic asymptotic vertical fringes\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    // Tangent function with periodic poles\n"
        "    float val = tan(input.uv.x * 4.0 + t * 2.0);\n"
        "    float clamped_val = clamp(val * 0.2 + 0.5, 0.0, 1.0);\n"
        "    \n"
        "    float3 col = float3(clamped_val, 0.4, 1.0 - clamped_val);\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_15_asin.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 15: asin (Shader Model 3.0 Trigonometry)\n"
        "// Inverse sine function mapping curvature into spherical compression gradient\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float x = clamp(input.uv.x, -0.99, 0.99);\n"
        "    float as = asin(x) / 1.570796; // Normalize [-pi/2, pi/2] to [-1, 1]\n"
        "    \n"
        "    float wave = sin(as * 6.28318 - t * 3.0) * 0.5 + 0.5;\n"
        "    float3 col = float3(as * 0.5 + 0.5, wave, 1.0 - wave);\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_16_acos.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 16: acos (Shader Model 3.0 Trigonometry)\n"
        "// Inverse cosine function mapping vertical coordinate into linear angular ramp [0, PI]\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float y = clamp(input.uv.y, -0.99, 0.99);\n"
        "    float ac = acos(y) / 3.14159265; // Normalize [0, PI] to [0, 1]\n"
        "    \n"
        "    float pulse = sin(ac * 12.0 - t * 4.0) * 0.5 + 0.5;\n"
        "    float3 col = float3(ac, pulse * 0.8, 1.0 - ac);\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_17_atan.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 17: atan (Shader Model 3.0 Trigonometry)\n"
        "// Inverse tangent function generating smooth S-curve sigmoid saturation\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    // Normalized input where polynomial approximation produces smooth S-curve\n"
        "    float at = atan(input.uv.x * 1.5 + sin(t * 2.0) * 0.5) / 1.570796;\n"
        "    float norm_at = clamp(at * 0.5 + 0.5, 0.0, 1.0);\n"
        "    \n"
        "    // Smooth S-curve chromatic gradient\n"
        "    float3 col = float3(norm_at, sin(norm_at * 3.14159265), 1.0 - norm_at);\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_18_atan2.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 18: atan2 (Shader Model 3.0 Trigonometry)\n"
        "// 4-Quadrant Arc Tangent computing 360-degree rotating chromatic hue wheel\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    // Robust 4-quadrant atan2 computation with zero-division immunity\n"
        "    float2 p = input.uv;\n"
        "    float abs_x = abs(p.x) + 1e-5;\n"
        "    float abs_y = abs(p.y);\n"
        "    float t_max = max(abs_x, abs_y);\n"
        "    float t_min = min(abs_x, abs_y);\n"
        "    float q = t_min / t_max;\n"
        "    float q2 = q * q;\n"
        "    float poly = q * (0.97239411 - 0.19194795 * q2);\n"
        "    \n"
        "    // Swap angle if |y| > |x| to prevent vertical divergence\n"
        "    float angle = (abs_y > abs_x) ? (1.5707963 - poly) : poly;\n"
        "    if (p.x < 0.0) angle = 3.14159265 - angle;\n"
        "    if (p.y < 0.0) angle = -angle;\n"
        "    \n"
        "    float norm_angle = frac((angle + t * 2.0) / 6.2831853);\n"
        "    \n"
        "    // Convert normalized hue to continuous RGB color wheel\n"
        "    float r = abs(norm_angle * 6.0 - 3.0) - 1.0;\n"
        "    float g = 2.0 - abs(norm_angle * 6.0 - 2.0);\n"
        "    float b = 2.0 - abs(norm_angle * 6.0 - 4.0);\n"
        "    float3 hue_col = saturate(float3(r, g, b));\n"
        "    \n"
        "    float rad = saturate(1.0 - length(input.uv));\n"
        "    float3 col = hue_col * rad;\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_19_radians.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 19: radians (Shader Model 3.0 Trigonometry)\n"
        "// Degree to radian conversion scaling 360-degree compass into 12 circular sectors\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    // Robust 4-quadrant polar angle computation\n"
        "    float2 p = input.uv;\n"
        "    float abs_x = abs(p.x) + 1e-5;\n"
        "    float abs_y = abs(p.y);\n"
        "    float t_max = max(abs_x, abs_y);\n"
        "    float t_min = min(abs_x, abs_y);\n"
        "    float q = t_min / t_max;\n"
        "    float q2 = q * q;\n"
        "    float poly = q * (0.97239411 - 0.19194795 * q2);\n"
        "    float angle = (abs_y > abs_x) ? (1.5707963 - poly) : poly;\n"
        "    if (p.x < 0.0) angle = 3.14159265 - angle;\n"
        "    if (p.y < 0.0) angle = -angle;\n"
        "    \n"
        "    float angle_deg = frac((angle + t * 2.0) / 6.2831853) * 360.0;\n"
        "    // Test native radians(deg)\n"
        "    float angle_rad = radians(angle_deg);\n"
        "    \n"
        "    float sector = floor(angle_deg / 30.0) / 12.0;\n"
        "    float3 col = float3(sector, sin(angle_rad) * 0.5 + 0.5, cos(angle_rad) * 0.5 + 0.5);\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_20_degrees.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 20: degrees (Shader Model 3.0 Trigonometry)\n"
        "// Radian to degree conversion verifying reciprocal angle calibration steps\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float rad = input.uv.x * 3.14159265;\n"
        "    // Test native degrees(rad)\n"
        "    float deg = degrees(rad);\n"
        "    \n"
        "    float normalized_deg = frac(deg / 360.0 + t * 0.2);\n"
        "    float3 col = float3(normalized_deg, frac(deg / 60.0), 1.0 - normalized_deg);\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_21_exp2.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 21: exp2 (Shader Model 3.0 Exponential & Logarithmic)\n"
        "// Hardware EX2 2^x exponential curve generating steep power illumination ramp\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float x = (input.uv.x * 0.5 + 0.5) * 3.0 - 2.0; // [-2.0, 1.0]\n"
        "    // Hardware EX2\n"
        "    float val = exp2(x + sin(t) * 0.5);\n"
        "    \n"
        "    float3 col = float3(val * 0.8, val * 0.4, val * 0.2);\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_22_exp.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 22: exp (Shader Model 3.0 Exponential & Logarithmic)\n"
        "// Natural exponential e^x calculating Gaussian radial point light bloom\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float r_sq = dot(input.uv, input.uv) * (3.0 + sin(t * 2.0));\n"
        "    // Natural exp(-r_sq)\n"
        "    float bloom = exp(-r_sq);\n"
        "    \n"
        "    float3 col = float3(bloom * 1.0, bloom * 0.8, bloom * 0.4);\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_23_log2.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 23: log2 (Shader Model 3.0 Exponential & Logarithmic)\n"
        "// Hardware LG2 base-2 logarithm compressing dynamic range across horizontal axis\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float x = max((input.uv.x * 0.5 + 0.5) * 16.0, 0.0625);\n"
        "    // Hardware LG2\n"
        "    float l2 = (log2(x) + 4.0) / 8.0; // Map [-4, 4] to [0, 1]\n"
        "    \n"
        "    float wave = sin(l2 * 12.0 - t * 3.0) * 0.5 + 0.5;\n"
        "    float3 col = float3(l2, wave, 1.0 - l2);\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_24_log.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 24: log (Shader Model 3.0 Exponential & Logarithmic)\n"
        "// Natural logarithm ln(x) producing radial tone-mapping compression rings\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float r = max(length(input.uv) * 8.0, 0.05);\n"
        "    // Natural ln(r)\n"
        "    float ln_val = saturate((log(r) + 2.0) / 4.0);\n"
        "    \n"
        "    float pulse = cos(ln_val * 16.0 - t * 4.0) * 0.5 + 0.5;\n"
        "    float3 col = float3(ln_val * 0.7, pulse, 0.9 - ln_val * 0.5);\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_25_log10.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 25: log10 (Shader Model 3.0 Exponential & Logarithmic)\n"
        "// Base-10 logarithm generating decibel-style decade intensity steps\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float x = max((input.uv.x * 0.5 + 0.5) * 100.0, 0.1);\n"
        "    // Base-10 logarithm: log10(x)\n"
        "    float l10 = (log10(x) + 1.0) / 3.0; // Map [-1, 2] to [0, 1]\n"
        "    \n"
        "    float step_band = floor(l10 * 6.0) / 6.0;\n"
        "    float3 col = float3(l10, step_band, 1.0 - l10);\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_26_pow.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 26: pow (Shader Model 3.0 Exponential & Logarithmic)\n"
        "// Power exponentiation x^y focusing high-specular Phong reflection highlight spot\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float2 light_pos = float2(sin(t * 2.0) * 0.4, cos(t * 2.0) * 0.4);\n"
        "    float dist = length(input.uv - light_pos);\n"
        "    float base_light = max(0.0, 1.0 - dist * 1.5);\n"
        "    \n"
        "    // High exponent power curve (Phong specular)\n"
        "    float spec = pow(base_light, 16.0);\n"
        "    float3 col = float3(spec * 1.0, spec * 0.9, spec * 0.6) + float3(0.05, 0.1, 0.2);\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_27_floor.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 27: floor (Shader Model 3.0 Rounding & Truncation)\n"
        "// Hardware FLR instruction quantizing coordinates into 12x12 retro mosaic grid\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    // Hardware FLR\n"
        "    float2 cell = floor(input.uv * 12.0) / 12.0;\n"
        "    \n"
        "    float val = sin((cell.x + cell.y) * 3.14159 + t * 3.0) * 0.5 + 0.5;\n"
        "    float3 col = float3(cell.x * 0.5 + 0.5, val, cell.y * 0.5 + 0.5);\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_28_ceil.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 28: ceil (Shader Model 3.0 Rounding & Truncation)\n"
        "// Ceiling function (-FLR(-x)) producing quantized upper stair-stepped color blocks\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    // Hardware Ceil: -floor(-x)\n"
        "    float2 cell = ceil(input.uv * 12.0) / 12.0;\n"
        "    \n"
        "    float val = cos((cell.x - cell.y) * 3.14159 + t * 3.0) * 0.5 + 0.5;\n"
        "    float3 col = float3(val, cell.x * 0.5 + 0.5, cell.y * 0.5 + 0.5);\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_29_frac.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 29: frac / fract (Shader Model 3.0 Rounding & Truncation)\n"
        "// Hardware FRC instruction decomposing coordinate space into repeating sawtooth ramps\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    // Hardware FRC: x - floor(x)\n"
        "    float2 f = frac((input.uv + float2(t * 0.2, t * 0.1)) * 6.0);\n"
        "    \n"
        "    float3 col = float3(f.x, f.y, 0.5 * (f.x + f.y));\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_30_round.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 30: round (Shader Model 3.0 Rounding & Truncation)\n"
        "// Nearest integer rounding (floor(x + 0.5)) creating discrete color quantization bands\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float r = length(input.uv) * 6.0;\n"
        "    // Nearest integer rounding: round(r)\n"
        "    float rounded_r = round(r + sin(t) * 0.5) / 6.0;\n"
        "    \n"
        "    float3 col = float3(rounded_r, 1.0 - rounded_r, frac(rounded_r * 3.0));\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_31_trunc.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 31: trunc (Shader Model 3.0 Rounding & Truncation)\n"
        "// Truncation towards zero generating symmetric step plateaus with double-width origin band\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float2 tr = trunc(input.uv * 5.0) / 5.0;\n"
        "    \n"
        "    float val = sin((tr.x + tr.y) * 4.0 + t * 3.0) * 0.5 + 0.5;\n"
        "    float3 col = float3(tr.x * 0.5 + 0.5, val, tr.y * 0.5 + 0.5);\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_32_sign.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 32: sign (Shader Model 3.0 Rounding & Truncation)\n"
        "// Tri-state Sign function (-1, 0, +1) mapping 4 coordinate quadrants to primary color blocks\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float2 s = sign(input.uv + float2(sin(t) * 0.3, cos(t) * 0.3));\n"
        "    \n"
        "    // Quadrant mapping: (+1,+1)=Yellow, (-1,+1)=Green, (-1,-1)=Blue, (+1,-1)=Red\n"
        "    float3 col = float3(s.x > 0.0 ? 1.0 : 0.0, s.y > 0.0 ? 1.0 : 0.0, s.x < 0.0 ? 1.0 : 0.0);\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_33_min.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 33: min (Shader Model 3.0 Clamping & Interpolation)\n"
        "// Hardware MIN instruction extracting geometric intersection of two moving spotlights\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float2 p1 = float2(-0.3 + sin(t * 2.0) * 0.2, 0.0);\n"
        "    float2 p2 = float2( 0.3 - sin(t * 2.0) * 0.2, 0.0);\n"
        "    \n"
        "    float d1 = max(0.0, 1.0 - length(input.uv - p1) * 2.0);\n"
        "    float d2 = max(0.0, 1.0 - length(input.uv - p2) * 2.0);\n"
        "    \n"
        "    // Hardware MIN computes intersection\n"
        "    float inter = min(d1, d2);\n"
        "    float3 col = float3(inter * 1.0, inter * 0.8, inter * 0.2) + float3(d1 * 0.2, 0.0, d2 * 0.2);\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_34_max.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 34: max (Shader Model 3.0 Clamping & Interpolation)\n"
        "// Hardware MAX instruction computing geometric union illumination of two moving lights\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float2 p1 = float2(-0.3 + sin(t * 2.0) * 0.2, 0.0);\n"
        "    float2 p2 = float2( 0.3 - sin(t * 2.0) * 0.2, 0.0);\n"
        "    \n"
        "    float d1 = max(0.0, 1.0 - length(input.uv - p1) * 2.0);\n"
        "    float d2 = max(0.0, 1.0 - length(input.uv - p2) * 2.0);\n"
        "    \n"
        "    // Hardware MAX computes union envelope\n"
        "    float u = max(d1, d2);\n"
        "    float3 col = float3(u * 0.9, u * 0.5, u * 1.0);\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_35_clamp.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 35: clamp (Shader Model 3.0 Clamping & Interpolation)\n"
        "// Interval clamping (MIN + MAX) bounding animated wave peaks between 0.2 and 0.8\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float wave = sin(input.uv.x * 8.0 - t * 3.0) * 0.5 + 0.5;\n"
        "    // Hardware Clamp: MIN(MAX(wave, 0.25), 0.75)\n"
        "    float clamped_w = clamp(wave, 0.25, 0.75);\n"
        "    \n"
        "    float3 col = float3(clamped_w, 0.6, 1.0 - clamped_w);\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_36_saturate.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 36: saturate (Shader Model 3.0 Clamping & Interpolation)\n"
        "// Hardware Output Saturation modifier (_SAT) locking high dynamic range values into [0, 1]\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float raw_val = (input.uv.x + sin(t) * 0.5) * 2.0; // Expands to [-3, +3]\n"
        "    // Hardware _SAT bit locks to [0.0, 1.0]\n"
        "    float sat_val = saturate(raw_val);\n"
        "    \n"
        "    float3 col = float3(sat_val, sat_val * 0.8, 1.0 - sat_val);\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_37_lerp.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 37: lerp / mix (Shader Model 3.0 Clamping & Interpolation)\n"
        "// Linear interpolation (MAD: a + weight*(b - a)) between Cyan and Magenta gradients\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float3 col_cyan    = float3(0.0, 0.9, 0.9);\n"
        "    float3 col_magenta = float3(0.9, 0.0, 0.9);\n"
        "    \n"
        "    float weight = saturate(input.uv.x * 0.5 + 0.5 + sin(t * 2.0) * 0.2);\n"
        "    // Single-cycle MAD interpolation\n"
        "    float3 result = lerp(col_cyan, col_magenta, weight);\n"
        "    \n"
        "    output.color = float4(result, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_38_step.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 38: step (Shader Model 3.0 Clamping & Interpolation)\n"
        "// Hardware SGE threshold step function splitting screen into razor-sharp binary halves\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float edge = sin(t * 2.0) * 0.5;\n"
        "    // Hardware SGE: step(edge, uv.x)\n"
        "    float s = step(edge, input.uv.x);\n"
        "    \n"
        "    float3 col = lerp(float3(0.1, 0.1, 0.3), float3(0.9, 0.8, 0.1), s);\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_39_smoothstep.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 39: smoothstep (Shader Model 3.0 Clamping & Interpolation)\n"
        "// Hermite cubic interpolation generating anti-aliased luminous circular ring\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float d = length(input.uv);\n"
        "    float r = 0.5 + 0.2 * sin(t * 2.0);\n"
        "    \n"
        "    // Hermite smoothstep for outer and inner borders\n"
        "    float ring = smoothstep(r - 0.1, r, d) - smoothstep(r, r + 0.1, d);\n"
        "    float3 col = float3(ring * 0.2, ring * 0.9, ring * 1.0);\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_40_dot2.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 40: dot (2D) (Shader Model 3.0 Vector Algebra)\n"
        "// Hardware DP2 2D dot product projecting UV vector onto rotating directional vector\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float2 dir = float2(cos(t * 1.5), sin(t * 1.5));\n"
        "    // Hardware DP2\n"
        "    float proj = dot(input.uv, dir);\n"
        "    float norm_proj = proj * 0.5 + 0.5;\n"
        "    \n"
        "    float3 col = float3(norm_proj, 0.5 + 0.5 * sin(proj * 6.28), 1.0 - norm_proj);\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_41_dot3.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 41: dot (3D) (Shader Model 3.0 Vector Algebra)\n"
        "// Hardware DP3 3D dot product calculating real-time Lambertian diffuse shaded 3D sphere\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float r_sq = dot(input.uv, input.uv);\n"
        "    if (r_sq < 0.64) {\n"
        "        float z = sqrt(0.64 - r_sq);\n"
        "        float3 normal = normalize(float3(input.uv.x, input.uv.y, z));\n"
        "        float3 light_dir = normalize(float3(sin(t * 2.0), cos(t * 2.0), 1.0));\n"
        "        \n"
        "        // Hardware DP3 for Lambertian diffuse\n"
        "        float diff = max(0.0, dot(normal, light_dir));\n"
        "        float3 col = float3(0.9, 0.4, 0.2) * diff + float3(0.05, 0.05, 0.1);\n"
        "        output.color = float4(col, 1.0);\n"
        "    } else {\n"
        "        output.color = float4(0.05, 0.05, 0.08, 1.0);\n"
        "    }\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_42_dot4.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 42: dot (4D) (Shader Model 3.0 Vector Algebra)\n"
        "// Hardware DP4 4D dot product evaluating 4D homogeneous transformation projection slice\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float4 v4 = float4(input.uv.x, input.uv.y, sin(t), cos(t));\n"
        "    float4 hyper_plane = float4(0.5, -0.5, 0.707, -0.707);\n"
        "    \n"
        "    // Hardware DP4\n"
        "    float d4 = dot(v4, hyper_plane);\n"
        "    float wave = sin(d4 * 8.0) * 0.5 + 0.5;\n"
        "    \n"
        "    float3 col = float3(wave, d4 * 0.5 + 0.5, 1.0 - wave);\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_43_cross.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 43: cross (Shader Model 3.0 Vector Algebra)\n"
        "// 3D Cross Product generating orthogonal surface normal vector map (tangent x bitangent)\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float3 tang   = normalize(float3(1.0, 0.0, sin(input.uv.x * 4.0 + t) * 0.5));\n"
        "    float3 bitang = normalize(float3(0.0, 1.0, cos(input.uv.y * 4.0 + t) * 0.5));\n"
        "    \n"
        "    // Swizzled MUL + MAD cross product: tang x bitang\n"
        "    float3 norm = cross(tang, bitang);\n"
        "    float3 col = norm * 0.5 + 0.5;\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_44_length.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 44: length (Shader Model 3.0 Vector Algebra)\n"
        "// Vector Euclidean Length (DP2 -> RSQ -> RCP) generating concentric distance contours\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float l = length(input.uv * 6.0);\n"
        "    float rings = sin(l - t * 4.0) * 0.5 + 0.5;\n"
        "    \n"
        "    float3 col = float3(saturate(l / 6.0), rings, 1.0 - rings);\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_45_distance.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 45: distance (Shader Model 3.0 Vector Algebra)\n"
        "// Euclidean distance between two moving orbital attractor points\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float2 p1 = float2(cos(t * 1.5) * 0.5, sin(t * 1.5) * 0.5);\n"
        "    float2 p2 = float2(-cos(t * 2.0) * 0.4, -sin(t * 2.0) * 0.4);\n"
        "    \n"
        "    float d1 = distance(input.uv, p1);\n"
        "    float d2 = distance(input.uv, p2);\n"
        "    \n"
        "    float field = sin((d1 - d2) * 8.0) * 0.5 + 0.5;\n"
        "    float3 col = float3(field * 0.8, (1.0 - d1 * 0.5), (1.0 - d2 * 0.5));\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_46_normalize.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 46: normalize (Shader Model 3.0 Vector Algebra)\n"
        "// Unit vector normalization encoding hemisphere normal coordinates into RGB\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float3 raw_vec = float3(input.uv.x, input.uv.y, 0.5 + 0.3 * sin(t * 2.0));\n"
        "    // Hardware normalization: v * RSQ(dot(v, v))\n"
        "    float3 n = normalize(raw_vec);\n"
        "    \n"
        "    float3 col = n * 0.5 + 0.5;\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_47_reflect.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 47: reflect (Shader Model 3.0 Optics & Physics)\n"
        "// Specular reflection vector (i - 2.0 * dot(i, n) * n) sampling simulated environment\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float r_sq = dot(input.uv, input.uv);\n"
        "    if (r_sq < 0.64) {\n"
        "        float z = sqrt(0.64 - r_sq);\n"
        "        float3 normal = normalize(float3(input.uv.x, input.uv.y, z));\n"
        "        float3 incident = float3(0.0, 0.0, -1.0);\n"
        "        \n"
        "        // Compute specular reflection vector\n"
        "        float3 refl = reflect(incident, normal);\n"
        "        \n"
        "        // Sample simulated panoramic stripes\n"
        "        float stripes = sin(refl.x * 12.0 + t * 3.0) * 0.5 + 0.5;\n"
        "        float3 col = float3(refl.y * 0.5 + 0.5, stripes, refl.z * 0.5 + 0.5);\n"
        "        output.color = float4(col, 1.0);\n"
        "    } else {\n"
        "        output.color = float4(0.08, 0.08, 0.12, 1.0);\n"
        "    }\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_48_refract.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 48: refract (Shader Model 3.0 Optics & Physics)\n"
        "// Snell's Law optical refraction bending background grid through glass sphere lens\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float r_sq = dot(input.uv, input.uv);\n"
        "    if (r_sq < 0.64) {\n"
        "        float z = sqrt(0.64 - r_sq);\n"
        "        float3 normal = normalize(float3(input.uv.x, input.uv.y, z));\n"
        "        float3 incident = float3(0.0, 0.0, -1.0);\n"
        "        \n"
        "        // Refraction with eta = 0.75 (glass/air)\n"
        "        float3 refr = refract(incident, normal, 0.75);\n"
        "        \n"
        "        float2 bg_uv = input.uv + refr.xy * 0.4;\n"
        "        float grid = sin(bg_uv.x * 16.0 + t * 2.0) * sin(bg_uv.y * 16.0) * 0.5 + 0.5;\n"
        "        float3 col = float3(grid * 0.2, grid * 0.8, grid * 1.0);\n"
        "        output.color = float4(col, 1.0);\n"
        "    } else {\n"
        "        float grid = sin(input.uv.x * 16.0 + t * 2.0) * sin(input.uv.y * 16.0) * 0.5 + 0.5;\n"
        "        output.color = float4(grid * 0.3, grid * 0.3, grid * 0.3, 1.0);\n"
        "    }\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_49_faceforward.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 49: faceforward (Shader Model 3.0 Optics & Physics)\n"
        "// Conditional normal orientation flipping surface normals to face the camera\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float3 normal = normalize(float3(input.uv.x, input.uv.y, 0.5));\n"
        "    float3 view_dir = normalize(float3(sin(t * 2.0), 0.0, -1.0));\n"
        "    \n"
        "    // Native faceforward(N, I, Ng)\n"
        "    float3 ff_norm = faceforward(normal, view_dir, normal);\n"
        "    float3 col = ff_norm * 0.5 + 0.5;\n"
        "    \n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_50_slt.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 50: slt / < (Shader Model 3.0 Relational Logic)\n"
        "// Hardware SLT (Set on Less Than) splitting diagonal coordinate domains\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float threshold = sin(t * 2.0) * 0.4;\n"
        "    // Hardware SLT: (uv.x < uv.y + threshold)\n"
        "    bool is_less = input.uv.x < (input.uv.y + threshold);\n"
        "    \n"
        "    float3 col = is_less ? float3(0.9, 0.2, 0.3) : float3(0.1, 0.7, 0.9);\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_51_sge.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 51: sge / >= (Shader Model 3.0 Relational Logic)\n"
        "// Hardware SGE (Set on Greater or Equal) evaluating circular threshold mask\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float radius = 0.5 + 0.2 * sin(t * 2.5);\n"
        "    // Hardware SGE: (length(uv) >= radius)\n"
        "    bool is_ge = length(input.uv) >= radius;\n"
        "    \n"
        "    float3 col = is_ge ? float3(0.2, 0.8, 0.4) : float3(0.8, 0.3, 0.9);\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_52_sgt.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 52: sgt / > (Shader Model 3.0 Relational Logic)\n"
        "// Hardware SGT (Set on Greater Than) generating dynamic binary zebra pattern\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float wave = sin((input.uv.x + input.uv.y) * 8.0 - t * 4.0);\n"
        "    // Hardware SGT: (wave > 0.0)\n"
        "    bool is_gt = wave > 0.0;\n"
        "    \n"
        "    float3 col = is_gt ? float3(0.95, 0.95, 0.95) : float3(0.05, 0.05, 0.05);\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_53_sle.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 53: sle / <= (Shader Model 3.0 Relational Logic)\n"
        "// Hardware SLE (Set on Less or Equal) rendering interior spotlight disc\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float radius = 0.45 + 0.15 * cos(t * 3.0);\n"
        "    // Hardware SLE: (length(uv) <= radius)\n"
        "    bool is_le = length(input.uv) <= radius;\n"
        "    \n"
        "    float3 col = is_le ? float3(1.0, 0.8, 0.1) : float3(0.1, 0.1, 0.2);\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_54_seq.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 54: seq / == (Shader Model 3.0 Relational Logic)\n"
        "// Hardware SEQ (Set on Equal) illuminating sharp scanning coincidence line\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float scan_pos = sin(t * 2.0) * 0.7;\n"
        "    // Hardware comparison simulating equality tolerance band\n"
        "    bool is_eq = abs(input.uv.x - scan_pos) < 0.02;\n"
        "    \n"
        "    float3 col = is_eq ? float3(0.2, 1.0, 0.5) : float3(0.05, 0.05, 0.1);\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_55_sne.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 55: sne / != (Shader Model 3.0 Relational Logic)\n"
        "// Hardware SNE (Set on Not Equal) illuminating everywhere except zero-axis line\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float axis_pos = cos(t * 2.0) * 0.5;\n"
        "    // Hardware SNE: (abs(uv.y - axis_pos) > 0.03)\n"
        "    bool is_ne = abs(input.uv.y - axis_pos) > 0.03;\n"
        "    \n"
        "    float3 col = is_ne ? float3(0.7, 0.3, 0.8) : float3(0.0, 0.0, 0.0);\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_56_deriv.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 56: Screen-Space Derivatives (ddx / ddy / fwidth)\n"
        "// Hardware 2x2 Pixel Quad Screen Derivatives detecting procedural edge contours\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float pattern = sin(length(input.uv * 10.0) - t * 4.0);\n"
        "    \n"
        "    // Hardware Screen-Space Quad Derivatives: DDX and DDY\n"
        "    float dx = abs(ddx(pattern));\n"
        "    float dy = abs(ddy(pattern));\n"
        "    float edge = (dx + dy) * 8.0;\n"
        "    \n"
        "    float3 col = float3(edge * 1.0, edge * 0.7, 0.2 + edge * 0.3);\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    },
    {
        "test_57_discard.fcg",
        "// =============================================================================\n"
        "// PS3 RSX Test 57: discard / KIL (Shader Model 3.0 Fragment Conditional Pixel Kill)\n"
        "// Hardware KIL instruction punching perforated circular holes through the screen\n"
        "// =============================================================================\n"
        "\n"
        "struct FragmentInput {\n"
        "    float2 uv : TEXCOORD0;\n"
        "};\n"
        "\n"
        "struct FragmentOutput {\n"
        "    float4 color : COLOR0;\n"
        "};\n"
        "\n"
        "FragmentOutput main(FragmentInput input, uniform float4 time_param) {\n"
        "    FragmentOutput output;\n"
        "    float t = time_param.x;\n"
        "    \n"
        "    float2 grid_uv = frac(input.uv * 8.0) - 0.5;\n"
        "    float hole_dist = length(grid_uv);\n"
        "    \n"
        "    // Hardware KIL / Discard on circular holes\n"
        "    if (hole_dist < (0.35 + 0.1 * sin(t * 3.0))) {\n"
        "        discard;\n"
        "    }\n"
        "    \n"
        "    float3 col = float3(0.9, 0.6, 0.2);\n"
        "    output.color = float4(col, 1.0);\n"
        "    return output;\n"
        "}\n"
    }
};

int main(int argc, char* argv[]) {
    char out_dir[MAX_PATH_LEN] = "shaders";

    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--output-dir") == 0 && i + 1 < argc) {
            strncpy(out_dir, argv[++i], sizeof(out_dir) - 1);
        } else if (strcmp(argv[i], "--help") == 0) {
            printf("Usage: %s [--output-dir <directory>]\n", argv[0]);
            return 0;
        }
    }

    mkdir(out_dir, 0755);
    size_t count = sizeof(g_shaders) / sizeof(g_shaders[0]);

    for (size_t i = 0; i < count; i++) {
        char filepath[MAX_PATH_LEN];
        snprintf(filepath, sizeof(filepath), "%s/%s", out_dir, g_shaders[i].filename);
        FILE* fp = fopen(filepath, "w");
        if (!fp) {
            fprintf(stderr, "[ERROR] Failed to create %s\n", filepath);
            return 1;
        }
        fputs(g_shaders[i].content, fp);
        fclose(fp);
        printf("Generated %s\n", filepath);
    }

    printf("Total shaders generated: %zu\n", count);
    return 0;
}
