/**
 * PS3 Reality Synthesizer (RSX) - Shader Model 3.0 Conformance Test Suite Data
 * Autogenerated metadata and binary lookup table for all 57 test scenes.
 */

#ifndef __TEST_SUITE_DATA_H__
#define __TEST_SUITE_DATA_H__

#include <stdint.h>
#include <stdbool.h>
#include <rsx/rsx_program.h>

#define TOTAL_TEST_COUNT 57

typedef struct {
    int         id;
    const char* name;
    const char* category;
    const char* opcode;
    const char* visual_desc;
    bool        is_stub;
    bool        is_sphere_rt;
    const uint8_t* fpo_data;
    uint32_t    fpo_size;
} TestSuiteMetadata;

extern const TestSuiteMetadata g_test_suite_entries[TOTAL_TEST_COUNT];

#endif /* __TEST_SUITE_DATA_H__ */
